### ISSUE TITLE
修改camera为全屏

### ISSUE THREAD

**Issue by StarOfLife** [fluttercandies/scan_barcode#1]
camera_image_widget文件的组件返回修改为如下即可：
```   
 return AspectRatio(
      aspectRatio: controller.value.aspectRatio,
      child: GestureDetector(
        onTapDown: (details) async {
          // click to auto focus
          await controller.setFocusMode(FocusMode.locked);
          await controller.setFocusMode(FocusMode.auto);
        },
        child: CameraPreview(
          controller,
          child: widget.child,
        ),
      ),
    );
```

**Comment by CaiJingLong** [comment]
感谢反馈，之前的代码写的是有问题的，但只是没将 aspectRatio 设置给 else 部分的 AspectRatio。

另外 aspectRatio 应该使用 controller.size.aspectRatio，这个方法是我写在扩展里的，因为要考虑设备的方向等很多因素，代码来自于 camera 包内  https://github.com/flutter/packages/blob/main/packages/camera/camera/lib/src/camera_preview.dart#L57-L80

所以，其实外部的约束做好，直接不包裹 AspectRatio 也是可行的。

---

全屏不全屏的更深层原因其实来自于原生部分的代码，安卓中很多 ResolutionPreset 在真机中是不可用的，会被降级处理。比如ultraHigh 应该是 2160p，但是很多时候会被降级为 720p，iOS 我没有实际调试过，但应该也会有降级处理的操作。

<img width="911" alt="image" src="https://github.com/fluttercandies/scan_barcode/assets/14145407/8011cf81-533f-4595-b0ed-15cfef2ed562">

camera 目前提供的是有限的预设，但实际上每个设备的预设是不同的，作为定制相机使用可能不足，但作为扫码来说，一般情况下建议使用 high(720p) 也就足够了

目前扫码时，medium 会有问题，反而是low在扫简单二维码时是可用的，我个人建议大部分情况下，竖屏是扫码用默认即可。

**Comment by CaiJingLong** [comment]
我提交了一个 0.2.1 版本

**Comment by StarOfLife** [comment]
感谢
